### ISSUE TITLE
Compile failed, Reference to Record is ambiguous

### ISSUE THREAD

**Issue by arnicas** [bennofs/wdumper#23]
Hello, I am not great with java issues - perhaps you have an idea how to get past this:

> Task :compileJava FAILED
.../wdumper/src/main/java/io/github/bennofs/wdumper/database/Database.java:300: error: reference to Record is ambiguous
    private final static Table<Record> DUMP_RUN_ZENODO = DUMP
                               ^
  both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
...wdumper/src/main/java/io/github/bennofs/wdumper/database/Database.java:307: error: reference to Record is ambiguous
    private static DumpRunZenodo recordToDumpRunZenodo(Record record) {
                                                       ^
  both interface org.jooq.Record in org.jooq and class java.lang.Record in java.lang match
2 errors

FAILURE: Build failed with an exception.

**Comment by bennofs** [comment]
This is an issue with Java 14. I will fix it shortly.

**Comment by arnicas** [comment]
thanks for your speediness! can't wait to try it 👍
