### ISSUE TITLE
All dumps blocked for a month

### ISSUE THREAD

**Issue by Camillo-Pellizzari** [bennofs/wdumper#29]
It seems that, after 22/4/2021, no dump has been completed (https://wdumps.toolforge.org/dumps?page=4); all dumps requested from 23/4/2021 are "not finished".

**Comment by lydiapintscher** [comment]
This seems to be a duplicate of #28.

**Comment by Camillo-Pellizzari** [comment]
Yes, it was a duplicate in fact.
