### ISSUE TITLE
DB_HOST parameter: which database?

### ISSUE THREAD

**Issue by kerphi** [bennofs/wdumper#30]
Hello,

Thanks for the good work !
I have a quesiton about DB_HOST and DB_* parameters. Which database is it about?
Is it about the internal wikibase database in cas you want to dump a custom wikibase instance?

best regards,

**Comment by bennofs** [comment]
It's a MariaDB database used by wdumper itself to store the queue of requested dumps, and metadata like title, creation time etc.

**Comment by kerphi** [comment]
Ok thank you!
