### ISSUE TITLE
Excessive storage use by Toolforge deployment

### ISSUE THREAD

**Issue by bd808** [bennofs/wdumper#31]
[T247449](https://phabricator.wikimedia.org/T247449) NFS utilization is up to 310.95 GB. I wonder if the various 2019 and 2020 dump files in $HOME/dumpfiles/wikidatawiki/ are still useful data?

**Comment by bennofs** [comment]
They're not, but they also don't use much space:

```
tools.wdumps@tools-sgebastion-07:~$ du -sch dumpfiles/wikidatawiki/
956K	dumpfiles/wikidatawiki/
```

**Comment by bennofs** [comment]
Would it help if I move the dumpfiles to /scratch?

**Comment by bd808** [comment]
Closing per the follow up at https://phabricator.wikimedia.org/T247449. Thank you for helping us keep NFS storage limping along for Toolforge. :)
